export subject: string[][] = [
    subjects1-1s: string[],
    subjects2-2s: string[];
]


const subjects1a: string[] = [
    'ARCHITETTURA DEGLI ELABORATORI E LABORATORIO',
    'FONDAMENTI DI INFORMATICA',
    'PROGRAMMAZIONE I E LABORATORIO',
    'ULTERIORI CONOSCENZE LINGUISTICHE',
    'ALGEBRA LINEARE E GEOMETRIA',
];
const subjects1b: string[] = [
    'ELEMENTI DI ANALISI MATEMATICA 1',
    'PROGRAMMAZIONE II',
    'ALGEBRA LINEARE E GEOMETRIA',
    'STRUTTURE DISCRETE'
];

export const subjects2a: string[] = [
    'ALGORITMI E LABORATORIO',
    'BASI DI DATI',
    'ELEMENTI DI ANALISI MATEMATICA 2',
    'INTERAZIONE E MULTIMEDIA',
];
export const subjects2b: string[] = [
    'INGEGNERIA DEL SOFTWARE',
    'RETI DI CALCOLATORI',
    'SISTEMI OPERATIVI',
];

export const subjects3a: string[] = [
    'CALCOLO NUMERICO',
    'COMPUTER GRAFICA',
    'DIGITAL FORENSICS',
    'FISICA',
    'INFORMATICA MUSICALE',
    'INTERNET SECURITY',
    'INTRODUZIONE AL DATA MINING',
    'IT LAW',
];

export const subjects3b: string[] = [
    'LABORATORIO DI SISTEMI A MICROCONTROLLORE',
    'METODI MATEMATICI E STATISTICI',
    'PROGRAMMAZIONE MOBILE',
    'PROGRAMMAZIONE PARALLELA SU ARCHITETTURE GPU',
    'SISTEMI CENTRALI',
    'SOCIAL MEDIA MANAGEMENT',
    'STARTUP DI IMPRESA E MODELLI DI BUSINESS',
    'SVILUPPO DI GIOCHI DIGITALI',
    'TECHNOLOGIES FOR ADVANCED PROGRAMMING',
    'TECNOLOGIE PER I SISTEMI DISTRIBUITI E IL WEB CON LABORATORIO',
    'WEB DEVELOPMENT'
];